/* eslint-disable */

'use strict';

/**
 * Commitizen adapter using AI commit generation
 * Generated by robo-commitizen
 */

const czAi = require('./index.cjs');

module.exports = {
  prompter: czAi.prompter,
};
